# Generated by Django 4.0.5 on 2022-06-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='Cours',
        ),
        migrations.AddField(
            model_name='cours',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='MyApp.level'),
        ),
    ]
