# Generated by Django 4.0.5 on 2022-06-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_level_cours_cours_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='Description',
            field=models.CharField(default='numbers', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='image',
            field=models.ImageField(default='1.png', upload_to=''),
            preserve_default=False,
        ),
    ]
