# Generated by Django 4.0.5 on 2022-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_level_description_level_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='IQ_Interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
